const d = (component, description, kind = 'shape', scale = 'meso', affects = 'geometry', confidence = 0.86, primitive = 'box') => ({
  component,
  description,
  kind,
  scale,
  affects,
  confidence,
  primitive,
});

export const profiles = {
  comcentre: {
    formLanguage: ['rectilinear', 'vertical', 'repetitive', 'late-modern'],
    structureKind: ['podium-and-tower', 'framed high-rise'],
    materials: ['pale painted concrete', 'dark ribbon glazing', 'steel', 'roof equipment'],
    palette: ['#dadbd6', '#7c8588', '#28383d', '#b44b45'],
    unknowns: ['Microwave-dish count and aiming changed across the building lifecycle', 'Hidden podium-to-tower connection', 'Rear service and roof-plant dimensions'],
    details: [
      d('tower-frame', 'Tall rectilinear slab framed by broad pale concrete piers around a recessed office grid', 'silhouette', 'macro', 'geometry', 0.97),
      d('equipment-podium', 'Five-storey two-wing equipment podium wraps a recessed central entrance and plaza', 'mass', 'macro', 'geometry', 0.88),
      d('roof-crown', 'Deep stepped telecommunications crown combines an upper slit, logo panel, dark bands and sloped terrace canopy', 'silhouette', 'macro', 'geometry', 0.94),
      d('east-service-core', 'Opaque full-height service core forming one blank side elevation', 'mass', 'meso', 'geometry', 0.91),
      d('west-service-core', 'Matching opaque service core on the opposite side', 'mass', 'meso', 'geometry', 0.82),
      d('window-ribbons', 'Dense horizontal office-window ribbons repeated over roughly thirty storeys', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('vertical-mullions', 'Fine vertical mullion grid subdividing each glazed ribbon', 'repetition', 'micro', 'geometry', 0.88, 'instanced-cluster'),
      d('top-vent-band', 'Narrow ventilation band between the glazing stack and crown', 'surface-detail', 'micro', 'geometry', 0.84),
      d('rooftop-space-frame', 'Full-width open steel lattice rises above the crown as the defining roof silhouette', 'identity-feature', 'macro', 'geometry', 0.93, 'assembled-solid'),
      d('microwave-dishes', 'Representative opening-era row of directional parabolic dishes mounted across the lattice', 'attachment', 'meso', 'geometry', 0.83, 'revolved-profile'),
      d('podium-louvres', 'Long horizontal equipment louvres across the podium faces', 'repetition', 'meso', 'geometry', 0.82, 'instanced-cluster'),
      d('glazed-entrance-rotunda', 'Curved glazed entrance lobby and projecting canopy anchor the central arrival bay', 'identity-feature', 'meso', 'geometry', 0.87, 'revolved-profile'),
      d('entrance-plaza', 'Recessed base and plaza plane beneath mature roadside trees', 'contact', 'meso', 'geometry', 0.72),
    ],
  },
  'national-theatre': {
    formLanguage: ['heroic-modernist', 'folded-plane', 'axial', 'symbolic'],
    structureKind: ['cantilevered auditorium', 'facade-and-roof shell'],
    materials: ['fair concrete', 'red brick infill', 'painted steel', 'water'],
    palette: ['#d9d1bd', '#9a4d40', '#efe6cf', '#4f8fa5', '#5f6462'],
    unknowns: ['Rear auditorium depth', 'Backstage layout', 'Exact roof truss profile'],
    details: [
      d('five-point-facade', 'Five soaring pointed bays form the unmistakable national-symbol facade', 'silhouette', 'macro', 'geometry', 0.99, 'extrude'),
      d('cantilever-roof', 'Deep wedge-shaped roof cantilevers back toward Fort Canning', 'silhouette', 'macro', 'geometry', 0.94, 'extrude'),
      d('auditorium-volume', 'Semi-open auditorium volume sits beneath the roof behind the facade', 'mass', 'macro', 'geometry', 0.72),
      d('concrete-fins', 'Slender pale structural fins define the five facade points', 'repetition', 'meso', 'geometry', 0.97, 'instanced-cluster'),
      d('red-infill-panels', 'Warm red triangular infill planes sit between the concrete fins', 'color-zone', 'meso', 'material', 0.96, 'extrude'),
      d('side-colonnade', 'Low side galleries use evenly spaced slender columns', 'repetition', 'meso', 'geometry', 0.86, 'instanced-cluster'),
      d('crescent-fountain', 'Crescent sculpture and circular basin anchor the forecourt', 'identity-feature', 'meso', 'geometry', 0.96, 'curve-sweep'),
      d('water-jets', 'Tall central jet with repeated arcing side jets', 'attachment', 'micro', 'geometry', 0.91, 'curve-sweep'),
      d('terraced-forecourt', 'Broad steps and raised public deck mediate the sloping site', 'contact', 'meso', 'geometry', 0.85),
      d('vertical-screens', 'Dense vertical screens line the low front galleries', 'repetition', 'micro', 'geometry', 0.8, 'instanced-cluster'),
      d('roof-edge-rib', 'Thin pale rim traces the roof wedge against the sky', 'edge-detail', 'micro', 'geometry', 0.83, 'curve-sweep'),
    ],
  },
  'national-library-stamford': {
    formLanguage: ['tropical-modernist', 'rectilinear', 'courtyard', 'brick'],
    structureKind: ['T-plan civic block', 'reinforced concrete frame with brick infill'],
    materials: ['red brick', 'painted concrete', 'dark glazing', 'metal lattice'],
    palette: ['#a65848', '#d7cfbd', '#61716c', '#785e4b', '#d9c9a6'],
    unknowns: ['Exact rear service elevations', 'Full T-plan dimensions', 'Original versus late courtyard furniture'],
    details: [
      d('main-brick-wing', 'Long red-brick library wing with three stacked window bands', 'mass', 'macro', 'geometry', 0.96),
      d('cross-wing', 'Taller cross-wing projects forward and closes one side of the courtyard', 'mass', 'macro', 'geometry', 0.91),
      d('entrance-porch', 'Broad flat entrance canopy projects over the curved arrival drive', 'silhouette', 'macro', 'geometry', 0.97),
      d('brick-porch-piers', 'Chunky square brick piers support the entrance canopy', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('window-bands', 'Deep-set horizontal window bands repeat across the red masonry', 'repetition', 'meso', 'geometry', 0.95, 'instanced-cluster'),
      d('end-lattice-screen', 'Tall decorative concrete lattice fills the cross-wing end bay', 'identity-feature', 'meso', 'geometry', 0.93, 'instanced-cluster'),
      d('courtyard-void', 'Open-air internal courtyard creates the key negative space', 'negative-space', 'macro', 'geometry', 0.9),
      d('courtyard-fountain', 'Small tiered white fountain stands near the court centre', 'identity-feature', 'micro', 'geometry', 0.84, 'revolved-profile'),
      d('roof-parapets', 'Low flat parapets cap the brick masses', 'edge-detail', 'micro', 'geometry', 0.91),
      d('external-stair', 'Secondary external stair and landing connect a rear wing', 'attachment', 'meso', 'geometry', 0.76, 'assembled-solid'),
      d('brick-vent-course', 'Small square vents form a low repeated course near the base', 'repetition', 'micro', 'geometry', 0.86, 'instanced-cluster'),
    ],
  },
  'van-kleef-aquarium': {
    formLanguage: ['low-modernist', 'asymmetric', 'horizontal', 'landscaped'],
    structureKind: ['split-level public pavilion', 'masonry and concrete frame'],
    materials: ['pink-white render', 'perforated concrete screen', 'dark glazing', 'brick-red steps'],
    palette: ['#e6c9b8', '#e8dfcf', '#7d8d86', '#a97865', '#4e6258'],
    unknowns: ['Interior aquarium layout', 'Rear slope retaining structure', 'Exact phase of clock-tower remodelling'],
    details: [
      d('long-display-wing', 'Long low wing stretches horizontally along the foot of the hill', 'mass', 'macro', 'geometry', 0.95),
      d('entrance-block', 'Taller two-storey entrance block projects at the right', 'mass', 'macro', 'geometry', 0.96),
      d('landscaped-terrace', 'Raised lawn and planted terrace form the building base', 'contact', 'macro', 'geometry', 0.86),
      d('entrance-piers', 'Four deep rectangular piers create a shaded entrance loggia', 'repetition', 'meso', 'geometry', 0.98, 'instanced-cluster'),
      d('perforated-screen', 'Small repeated perforations texture the long wing wall', 'repetition', 'micro', 'geometry', 0.93, 'instanced-cluster'),
      d('clerestory-openings', 'Small square openings run beneath the long wing roof', 'repetition', 'micro', 'geometry', 0.9, 'instanced-cluster'),
      d('broad-entry-stair', 'Broad red-toned entrance steps span the loggia width', 'contact', 'meso', 'geometry', 0.94, 'assembled-solid'),
      d('right-window-bands', 'Two compact horizontal window groups puncture the entrance block', 'repetition', 'meso', 'geometry', 0.91, 'instanced-cluster'),
      d('flat-roof-slabs', 'Thin flat roofs maintain the long low silhouette', 'edge-detail', 'meso', 'geometry', 0.95),
      d('crest-emblem', 'Small red crest marks the otherwise plain entrance wall', 'identity-feature', 'micro', 'material', 0.82, 'extrude'),
      d('forecourt-planters', 'Low brick planters and tropical specimens edge the stair', 'repetition', 'micro', 'geometry', 0.79, 'instanced-cluster'),
    ],
  },
  'former-national-stadium': {
    formLanguage: ['elliptical', 'repetitive-structural', 'open-bowl', 'civic-megastructure'],
    structureKind: ['reinforced-concrete stadium bowl', 'cantilevered west grandstand'],
    materials: ['weathered concrete', 'dark seating', 'red track', 'green turf', 'steel floodlights'],
    palette: ['#a7aaa2', '#444b4c', '#b44b48', '#5d8a5d', '#d8d5c8'],
    unknowns: ['Exact seat-bay count', 'Concourse room layout', 'Canopy structural section'],
    details: [
      d('elliptical-bowl', 'Open elliptical seating bowl defines the overall silhouette and void', 'silhouette', 'macro', 'geometry', 0.98, 'lathe'),
      d('west-grandstand', 'Single taller covered grandstand anchors the west side', 'mass', 'macro', 'geometry', 0.94, 'extrude'),
      d('track-and-field', 'Red oval running track surrounds a rectangular green pitch', 'color-zone', 'macro', 'geometry', 0.99, 'extrude'),
      d('concourse-ring', 'Continuous low concourse ring supports the seating bowl', 'mass', 'macro', 'geometry', 0.9, 'lathe'),
      d('lower-seating-tier', 'Lower dark seating tier follows the inner oval', 'repetition', 'meso', 'geometry', 0.95, 'instanced-cluster'),
      d('upper-seating-tier', 'Upper stepped tier wraps most of the oval', 'repetition', 'meso', 'geometry', 0.95, 'instanced-cluster'),
      d('concrete-rakers', 'Exposed diagonal concrete raker frames repeat around the outside', 'repetition', 'meso', 'geometry', 0.98, 'instanced-cluster'),
      d('west-canopy', 'Shallow cantilever canopy shades the grandstand', 'silhouette', 'meso', 'geometry', 0.92, 'extrude'),
      d('scalloped-canopy-bays', 'Repeated shallow roof scallops articulate the front elevation', 'repetition', 'micro', 'geometry', 0.9, 'instanced-cluster'),
      d('floodlight-northwest', 'Tall tapered floodlight pylon at the northwest quadrant', 'attachment', 'meso', 'geometry', 0.96, 'assembled-solid'),
      d('floodlight-northeast', 'Tall tapered floodlight pylon at the northeast quadrant', 'attachment', 'meso', 'geometry', 0.96, 'assembled-solid'),
      d('floodlight-southwest', 'Tall tapered floodlight pylon at the southwest quadrant', 'attachment', 'meso', 'geometry', 0.96, 'assembled-solid'),
      d('floodlight-southeast', 'Tall tapered floodlight pylon at the southeast quadrant', 'attachment', 'meso', 'geometry', 0.96, 'assembled-solid'),
      d('entrance-stairs', 'Broad axial stairs cut through the external raker frame', 'contact', 'meso', 'geometry', 0.9, 'assembled-solid'),
      d('scoreboard', 'Rectangular scoreboard interrupts one seating sector', 'identity-feature', 'meso', 'geometry', 0.78),
      d('field-markings', 'White pitch and track markings supply scale and orientation', 'surface-detail', 'micro', 'material', 0.94, 'plane-card'),
    ],
  },
  'pearl-bank-apartments': {
    formLanguage: ['broken-cylinder', 'horseshoe', 'vertical', 'brutalist'],
    structureKind: ['radial shear-wall high-rise', 'podium-and-tower'],
    materials: ['cream concrete', 'dark glazing', 'ochre fins', 'green roof deck'],
    palette: ['#d6d0b9', '#b1ab91', '#405050', '#a98449', '#6f8a66'],
    unknowns: ['Interlocking apartment sections', 'Exact podium plan', 'Late facade alterations'],
    details: [
      d('horseshoe-tower', 'Tall open horseshoe tower must preserve the deep inner void', 'silhouette', 'macro', 'geometry', 0.99, 'extrude'),
      d('service-spine', 'Solid pale service spine closes one side of the broken cylinder', 'mass', 'macro', 'geometry', 0.96, 'extrude'),
      d('podium-carpark', 'Low broad podium supports the tower and landscaped court', 'mass', 'macro', 'geometry', 0.85),
      d('roof-plant', 'Stepped rooftop service blocks cap the radial tower', 'mass', 'macro', 'geometry', 0.86),
      d('inner-balcony-ribbons', 'Curved balcony ribbons stack densely inside the horseshoe', 'repetition', 'meso', 'geometry', 0.98, 'instanced-cluster'),
      d('outer-window-ribbons', 'Alternating windows and solid bands wrap the outer curve', 'repetition', 'meso', 'geometry', 0.97, 'instanced-cluster'),
      d('radial-party-fins', 'Deep vertical party-wall fins divide the tower into radial sectors', 'repetition', 'meso', 'geometry', 0.97, 'instanced-cluster'),
      d('ochre-service-strips', 'Narrow ochre vertical strips mark service edges', 'color-zone', 'meso', 'material', 0.91, 'extrude'),
      d('sky-park-band', 'A deeper communal band interrupts the residential repetition', 'identity-feature', 'meso', 'geometry', 0.89, 'extrude'),
      d('court-garden', 'Landscaped court sits at the bottom of the tall inner void', 'contact', 'meso', 'geometry', 0.84),
      d('open-cylinder-gap', 'The narrow opening between tower ends is a critical negative space', 'negative-space', 'macro', 'geometry', 0.99),
      d('balcony-parapets', 'Thin pale balcony parapets create strong horizontal shadow lines', 'repetition', 'micro', 'geometry', 0.95, 'instanced-cluster'),
      d('window-mullions', 'Small dark mullions subdivide the glazed bands', 'repetition', 'micro', 'geometry', 0.82, 'instanced-cluster'),
      d('roof-cylinders', 'Small circular rooftop plant forms punctuate the skyline', 'identity-feature', 'micro', 'geometry', 0.78, 'revolved-profile'),
      d('podium-ramp', 'Inclined vehicle ramp attaches to the podium edge', 'attachment', 'meso', 'geometry', 0.68, 'extrude'),
      d('hill-base', 'Steep green Pearl Hill setting exaggerates the tower height', 'contact', 'macro', 'geometry', 0.8),
    ],
  },
  'tanglin-shopping-centre': {
    formLanguage: ['long-horizontal', 'podium-and-slab', 'incremental-modernist', 'arcaded'],
    structureKind: ['retail podium with office additions', 'reinforced concrete frame'],
    materials: ['white render', 'pink-grey panels', 'dark glazing', 'green signage'],
    palette: ['#d8d7d0', '#b8a99f', '#4a5758', '#567563', '#8f9390'],
    unknowns: ['Construction phase boundaries', 'Rear loading elevation', 'Exact mature-complex plan'],
    details: [
      d('retail-podium', 'Long original retail podium establishes the street wall', 'mass', 'macro', 'geometry', 0.96),
      d('office-slab', 'Taller pale office slab rises behind the podium', 'mass', 'macro', 'geometry', 0.9),
      d('stepped-annex', 'Rounded stepped annex and terrace edge terminate one end', 'silhouette', 'macro', 'geometry', 0.82, 'extrude'),
      d('ground-arcade', 'Deep shaded ground-level retail arcade runs along the frontage', 'negative-space', 'meso', 'geometry', 0.96, 'extrude'),
      d('square-window-bays', 'Regular square windows sit within broad framed facade bays', 'repetition', 'meso', 'geometry', 0.94, 'instanced-cluster'),
      d('horizontal-ledges', 'Deep ledges split the podium and office additions', 'repetition', 'meso', 'geometry', 0.93, 'instanced-cluster'),
      d('clerestory-band', 'Dark continuous clerestory strip separates podium layers', 'color-zone', 'micro', 'material', 0.88, 'extrude'),
      d('entrance-stairs', 'Broad entrance stairs rise from the recessed pavement edge', 'contact', 'meso', 'geometry', 0.9, 'assembled-solid'),
      d('green-wordmark', 'Long green Tanglin Shopping Centre wordmark marks the planter edge', 'identity-feature', 'micro', 'geometry', 0.91, 'extrude'),
      d('arched-feature-window', 'Large arched glazed opening punctuates one entrance bay', 'identity-feature', 'meso', 'geometry', 0.84, 'extrude'),
      d('terrace-rail', 'Thin rails and planted ledges articulate the stepped roof terraces', 'edge-detail', 'micro', 'geometry', 0.76, 'curve-sweep'),
    ],
  },
  'amber-mansions': {
    formLanguage: ['Cape-Dutch-revival', 'bowed-corner', 'street-block', 'arcaded'],
    structureKind: ['masonry mixed-use mansion block', 'pitched-roof two-wing plan'],
    materials: ['white plaster', 'terracotta roof tile', 'dark timber', 'painted shopfront'],
    palette: ['#ded9cb', '#aa6d55', '#66584c', '#3f4745', '#b99a75'],
    unknowns: ['Rear courtyard plan', 'Shop-bay depths', 'Period-specific signage set'],
    details: [
      d('bowed-corner-block', 'Three-storey bowed corner turns Orchard Road into Penang Lane', 'silhouette', 'macro', 'geometry', 0.97, 'extrude'),
      d('orchard-road-wing', 'Long three-storey wing extends down Orchard Road', 'mass', 'macro', 'geometry', 0.94),
      d('penang-lane-wing', 'Longer roofed wing follows the curve of Penang Lane', 'mass', 'macro', 'geometry', 0.93, 'extrude'),
      d('corner-dutch-gable', 'Large named Cape Dutch gable crowns the bowed corner', 'identity-feature', 'meso', 'geometry', 0.99, 'extrude'),
      d('repeated-dutch-gables', 'Smaller curved Dutch gables repeat along both rooflines', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('five-footway-arcade', 'Broad flattened arches form a continuous ground arcade', 'repetition', 'meso', 'geometry', 0.97, 'instanced-cluster'),
      d('corner-upper-arches', 'Two stacked arched openings animate the corner facade', 'identity-feature', 'meso', 'geometry', 0.96, 'extrude'),
      d('terracotta-roofs', 'Pitched terracotta-tile roofs sit behind the plaster gables', 'color-zone', 'meso', 'material', 0.94, 'extrude'),
      d('upper-window-rhythm', 'Regular rectangular windows repeat above the arcade', 'repetition', 'micro', 'geometry', 0.9, 'instanced-cluster'),
      d('corner-name-panel', 'AMBER MANSIONS lettering is split across the large gable', 'identity-feature', 'micro', 'geometry', 0.92, 'extrude'),
      d('shopfront-insets', 'Dark recessed shopfronts sit behind the pale street arches', 'negative-space', 'micro', 'geometry', 0.87, 'instanced-cluster'),
    ],
  },
  'eu-court': {
    formLanguage: ['Chinese-Art-Deco', 'stripped-classical', 'L-plan', 'corner-pavilion'],
    structureKind: ['masonry apartment block', 'retail arcade with residential floors'],
    materials: ['white render', 'dark timber windows', 'grey roof', 'painted shopfront'],
    palette: ['#deddd5', '#575c5b', '#8d8e86', '#b6afa1', '#454b4b'],
    unknowns: ['Courtyard service wing dimensions', 'Original shopfront treatment', 'Exact Chinese pavilion bracket geometry'],
    details: [
      d('hill-street-wing', 'Three-storey Hill Street wing forms one leg of the L', 'mass', 'macro', 'geometry', 0.94),
      d('stamford-road-wing', 'Three-storey Stamford Road wing forms the longer leg', 'mass', 'macro', 'geometry', 0.94),
      d('corner-tower', 'Slightly projecting corner bay rises above both wings', 'silhouette', 'macro', 'geometry', 0.98),
      d('chinese-roof-pavilion', 'Broad-eaved Chinese-style pavilion caps the corner tower', 'identity-feature', 'meso', 'geometry', 0.98, 'extrude'),
      d('ground-arcade', 'Flattened polygonal openings create a sheltered retail base', 'repetition', 'meso', 'geometry', 0.94, 'instanced-cluster'),
      d('grouped-windows', 'Tall grouped casement windows repeat in a restrained grid', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('vent-blocks', 'Small horizontal vent blocks sit beneath selected windows', 'repetition', 'micro', 'geometry', 0.91, 'instanced-cluster'),
      d('pavilion-brackets', 'Short projecting brackets support the layered pavilion eaves', 'attachment', 'micro', 'geometry', 0.88, 'instanced-cluster'),
      d('corner-parapet', 'Stepped parapet transitions from the wings into the pavilion', 'edge-detail', 'meso', 'geometry', 0.86, 'extrude'),
      d('rear-courtyard', 'L-shaped footprint encloses a rear service courtyard', 'negative-space', 'macro', 'geometry', 0.75),
      d('shopfront-recesses', 'Deep dark shopfront recesses contrast with the pale upper walls', 'negative-space', 'micro', 'geometry', 0.89, 'instanced-cluster'),
    ],
  },
  'alkaff-arcade': {
    formLanguage: ['Indo-Saracenic', 'vertical-frontispiece', 'arcaded', 'ornamental'],
    structureKind: ['long covered commercial passage', 'multi-storey masonry arcade'],
    materials: ['white plaster', 'dark openings', 'copper-toned domes', 'glass roof', 'patterned floor'],
    palette: ['#dedbd0', '#4d5150', '#7b6550', '#a8aaa4', '#6c6f69'],
    unknowns: ['Exact passage length', 'Rear Raffles Place facade', 'Dome surface finish'],
    details: [
      d('waterfront-frontispiece', 'Tall narrow waterfront frontispiece carries the paired domes', 'silhouette', 'macro', 'geometry', 0.97, 'extrude'),
      d('long-arcade-block', 'Long three-storey commercial block extends inland from the quay', 'mass', 'macro', 'geometry', 0.86),
      d('central-passage-void', 'Covered central shopping passage cuts through the full depth', 'negative-space', 'macro', 'geometry', 0.94, 'extrude'),
      d('glass-roof-spine', 'Glazed roof strip lights the long internal passage', 'silhouette', 'macro', 'geometry', 0.82, 'extrude'),
      d('left-onion-dome', 'Bulbous left dome caps an open corner pavilion', 'identity-feature', 'meso', 'geometry', 0.98, 'revolved-profile'),
      d('right-onion-dome', 'Matching right dome balances the facade', 'identity-feature', 'meso', 'geometry', 0.98, 'revolved-profile'),
      d('ground-horseshoe-arches', 'Large pointed horseshoe arches form the public entrances', 'repetition', 'meso', 'geometry', 0.98, 'instanced-cluster'),
      d('middle-arch-tier', 'Dense second-storey arches sit above patterned spandrels', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('upper-arch-tier', 'Smaller upper arches create a fine-grained top register', 'repetition', 'meso', 'geometry', 0.94, 'instanced-cluster'),
      d('corner-turrets', 'Slender corner turrets rise beside the dome pavilions', 'attachment', 'meso', 'geometry', 0.91, 'assembled-solid'),
      d('crenellated-parapet', 'Small merlon-like parapet pieces bridge the two domes', 'repetition', 'micro', 'geometry', 0.9, 'instanced-cluster'),
      d('patterned-spandrels', 'Alternating light-dark geometric spandrel bands separate arch tiers', 'surface-detail', 'micro', 'material', 0.9, 'instanced-cluster'),
      d('passage-shop-bays', 'Regular shuttered shop bays line both sides of the passage', 'repetition', 'meso', 'geometry', 0.92, 'instanced-cluster'),
      d('upper-galleries', 'Two narrow gallery levels overlook the central passage', 'negative-space', 'meso', 'geometry', 0.86, 'extrude'),
      d('passage-sign', 'Hanging shop sign crosses the passage in the late photograph', 'identity-feature', 'micro', 'geometry', 0.77, 'plane-card'),
      d('quay-entrance-step', 'Shallow raised threshold separates the facade from the quay edge', 'contact', 'micro', 'geometry', 0.74),
    ],
  },
  'beauty-world-market': {
    formLanguage: ['vernacular-incremental', 'irregular-roofscape', 'porous', 'market-lane'],
    structureKind: ['modular stall compound', 'timber and masonry shop rows'],
    materials: ['corrugated zinc', 'weathered timber', 'canvas awning', 'plaster', 'painted signs'],
    palette: ['#8b7c67', '#a6a194', '#607d72', '#765748', '#b6aa87'],
    unknowns: ['Exact full-site plan', 'Stall count by year', '1940s amusement-park structures'],
    details: [
      d('market-roof-cluster', 'Dense overlapping roof cluster forms the compound silhouette', 'silhouette', 'macro', 'geometry', 0.93, 'instanced-cluster'),
      d('main-market-lane', 'Narrow shaded lane organizes open shop fronts on both sides', 'negative-space', 'macro', 'geometry', 0.9, 'extrude'),
      d('tiong-hwa-cinema', 'Larger cinema block provides a legible anchor among small stalls', 'mass', 'macro', 'geometry', 0.76),
      d('performance-stage', 'Simple roofed getai/wayang stage recalls the compound performance use', 'mass', 'macro', 'geometry', 0.66, 'assembled-solid'),
      d('timber-stall-row', 'One-storey timber stalls repeat with irregular bay widths', 'repetition', 'meso', 'geometry', 0.9, 'instanced-cluster'),
      d('masonry-shop-row', 'More permanent pale masonry shops interrupt the timber rows', 'repetition', 'meso', 'geometry', 0.85, 'instanced-cluster'),
      d('corrugated-zinc-roofs', 'Rust-grey and pale corrugated roofs pitch in several directions', 'repetition', 'meso', 'geometry', 0.96, 'instanced-cluster'),
      d('green-canvas-awnings', 'Large green canvas sheets stretch over selected shop fronts', 'color-zone', 'meso', 'material', 0.94, 'plane-card'),
      d('deep-eave-shadows', 'Very deep eaves create dark thresholds along the lanes', 'negative-space', 'meso', 'geometry', 0.92, 'extrude'),
      d('open-merchandise-fronts', 'Shallow open shop fronts expose racks and counters to the lane', 'repetition', 'micro', 'geometry', 0.84, 'instanced-cluster'),
      d('hand-painted-signboards', 'Varied rectangular shop signboards sit above individual bays', 'repetition', 'micro', 'geometry', 0.88, 'instanced-cluster'),
      d('external-stair', 'Narrow utilitarian stair rises beside the market edge', 'attachment', 'meso', 'geometry', 0.84, 'assembled-solid'),
      d('utility-poles', 'Timber utility poles and loose overhead wires cross the roofscape', 'attachment', 'micro', 'geometry', 0.89, 'curve-sweep'),
      d('street-railings', 'Simple metal roadside railings define the compound edge', 'repetition', 'micro', 'geometry', 0.8, 'instanced-cluster'),
      d('market-counters', 'Counters and display tables project into the narrow lane', 'repetition', 'micro', 'geometry', 0.79, 'instanced-cluster'),
      d('patchwork-weathering', 'Mismatched roof and wall colours communicate incremental repair', 'surface-detail', 'micro', 'material', 0.9, 'plane-card'),
    ],
  },
  'tang-dynasty-city': {
    formLanguage: ['monumental-Chinese-revival', 'axial', 'walled-compound', 'layered-eaves'],
    structureKind: ['theme-park city gate and courtyard complex', 'masonry walls with timber-style pavilions'],
    materials: ['grey brick', 'dark ceramic tile', 'white plaster', 'dark timber', 'red banners'],
    palette: ['#777a72', '#2f3735', '#d6d2c2', '#5b4538', '#a84138'],
    unknowns: ['Complete 12-hectare plan', 'Unfinished attraction state', 'Clearance year discrepancy'],
    details: [
      d('crenellated-city-wall', 'Long high grey-brick wall creates the monumental street silhouette', 'silhouette', 'macro', 'geometry', 0.97, 'extrude'),
      d('central-gatehouse', 'Central arched gatehouse projects above the wall', 'mass', 'macro', 'geometry', 0.98),
      d('courtyard-hall', 'Two-storey white-and-dark-timber hall anchors the internal court', 'mass', 'macro', 'geometry', 0.92, 'assembled-solid'),
      d('seven-storey-pagoda', 'Slender multi-tier pagoda acts as the representative vertical landmark', 'silhouette', 'macro', 'geometry', 0.78, 'assembled-solid'),
      d('gate-arch', 'Deep round-headed stone arch forms the principal entrance void', 'negative-space', 'meso', 'geometry', 0.97, 'extrude'),
      d('gate-tile-roof', 'Broad dark tiled roof with upturned corners caps the gatehouse', 'identity-feature', 'meso', 'geometry', 0.97, 'extrude'),
      d('wall-merlons', 'Square crenellations repeat along the full wall top', 'repetition', 'meso', 'geometry', 0.98, 'instanced-cluster'),
      d('courtyard-tile-roofs', 'Layered dark roofs repeat across the internal halls', 'repetition', 'meso', 'geometry', 0.94, 'instanced-cluster'),
      d('timber-frame-bays', 'Dark timber posts and beams divide the pale hall facades', 'repetition', 'meso', 'geometry', 0.93, 'instanced-cluster'),
      d('arched-stone-bridge', 'Pale arched bridge crosses the formal pond', 'identity-feature', 'meso', 'geometry', 0.9, 'extrude'),
      d('formal-pond', 'Rectangular green pond and stone edge structure the courtyard', 'color-zone', 'meso', 'geometry', 0.9, 'extrude'),
      d('stone-lions', 'Paired guardian lions flank the main gate', 'attachment', 'micro', 'geometry', 0.91, 'assembled-solid'),
      d('red-banners', 'Large red calligraphic banners hang symmetrically on the wall', 'color-zone', 'micro', 'material', 0.95, 'plane-card'),
      d('white-balustrades', 'Pale carved-looking balustrades line bridge and forecourt edges', 'repetition', 'micro', 'geometry', 0.88, 'instanced-cluster'),
      d('ceremonial-plaza', 'Broad pale paved plaza preserves the strong axial approach', 'contact', 'macro', 'geometry', 0.94),
      d('watchtower-corners', 'Small roofed watchtowers punctuate selected wall corners', 'attachment', 'meso', 'geometry', 0.82, 'assembled-solid'),
    ],
  },
  'tank-road-railway-station': {
    formLanguage: ['colonial-utilitarian', 'low-linear', 'clock-tower-anchor', 'platform'],
    structureKind: ['timber passenger station', 'railway platform and yard'],
    materials: ['pale timber', 'red-brown roof tile', 'dark structural timber', 'steel rail', 'gravel'],
    palette: ['#d8d0bb', '#925f47', '#5c5043', '#545a58', '#8a806c'],
    unknowns: ['Boundary between 1903 and 1907 station fabric', 'Exact yard extent', 'Demolition date'],
    details: [
      d('station-range', 'Long low passenger range parallels Tank Road and the tracks', 'mass', 'macro', 'geometry', 0.96),
      d('clock-tower', 'Square central clock tower rises above the otherwise low roofline', 'silhouette', 'macro', 'geometry', 0.99, 'assembled-solid'),
      d('platform-and-track-bed', 'Covered platform and parallel track bed define the rail frontage', 'contact', 'macro', 'geometry', 0.96, 'extrude'),
      d('hipped-tile-roofs', 'Overlapping hipped roofs use warm red-brown tiles', 'color-zone', 'meso', 'material', 0.96, 'extrude'),
      d('clock-faces', 'Large pale circular clock faces occupy the tower sides', 'identity-feature', 'micro', 'geometry', 0.98, 'revolved-profile'),
      d('tower-louvres', 'Tall inset louvred panels sit below the clock faces', 'surface-detail', 'micro', 'geometry', 0.91, 'instanced-cluster'),
      d('platform-canopy', 'Long lightweight canopy shades the boarding edge', 'silhouette', 'meso', 'geometry', 0.93, 'extrude'),
      d('canopy-posts', 'Slender posts repeat along the platform canopy', 'repetition', 'meso', 'geometry', 0.95, 'instanced-cluster'),
      d('passenger-windows', 'Regular small windows punctuate the timber station walls', 'repetition', 'micro', 'geometry', 0.88, 'instanced-cluster'),
      d('parallel-rails', 'Multiple shiny steel rails run past the platform', 'repetition', 'meso', 'geometry', 0.97, 'curve-sweep'),
      d('sleepers', 'Close-spaced transverse sleepers give the track bed scale', 'repetition', 'micro', 'geometry', 0.94, 'instanced-cluster'),
      d('street-picket-fence', 'Low pale picket fence separates jinrickshaws from the station', 'repetition', 'micro', 'geometry', 0.93, 'instanced-cluster'),
      d('pedestrian-footbridge', 'Timber footbridge and stair connect across the tracks', 'attachment', 'meso', 'geometry', 0.86, 'assembled-solid'),
      d('station-signboard', 'Tank Road station name board sits near the platform edge', 'identity-feature', 'micro', 'geometry', 0.82, 'plane-card'),
      d('forecourt', 'Flat street forecourt accommodates waiting jinrickshaws', 'contact', 'meso', 'geometry', 0.9),
      d('yard-sidings', 'Branching sidings and points fan into the compact yard slice', 'repetition', 'meso', 'geometry', 0.85, 'curve-sweep'),
    ],
  },
};

export function tierFor(id) {
  return profiles[id].details.length >= 16 ? 'ultra-complex' : 'complex';
}
